language: node_js
node_js:
  - "lts"
install:
  - npm install
script:
  - npm run lint
  - npm run build:dev
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
